DHP/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    # Uncomment below Only If you want to call index.html page first
    # path('', views.index, name='index'),
    path('', include(('homepage.urls','home'),namespace='home')),
    path('home/', include(('homepage.urls','home'),namespace='home')),
    path('login/', include('login.urls')),
    path('manageUsers/', include('manageUsers.urls')),
    path('manageDestinations/',include('manageDestinations.urls')),
    path('manageResorts/',include('manageResorts.urls')),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('Rajasthan/', views.Rajasthan, name='index'),
    path('contactus/',views.contactus,name='contactus'),
    path('invoice/',views.Invoice,name='Invoice'),
    path('package/<int:id>/',views.openResorts,name='package'),
    path('package/<int:id>/<int:rid>/',views.openRooms,name='package'),
]

login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.index, name='index'),
    path('loginUser/', views.loginUser, name='loginUser'),
    path('signupUser/', views.signupUser, name='signupUser'),
]

manageUsers/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addNewUser', views.addNewUser, name='index'),
]

manageDestinations/models.py
from django.db import models

# Create your models here.

manageResorts/models.py
from django.db import models

# Create your models here.

manageUsers/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from firebaseConfig import database, Destination, Resort, Room, CurrentUser

Destinations : Destination  = database.child("Destinations").get().val()
Resorts : Resort = database.child("Resorts").get().val()
Rooms : Room = database.child("Rooms").get().val()

Filtered_Rooms = []
tempDName = ""

def index(request, template="homepage.html"):
    Destinations : Destination  = database.child("Destinations").get().val()
    Resorts : Resort = database.child("Resorts").get().val()
    Rooms : Room = database.child("Rooms").get().val()
    return render(request, template, {"Destinations": Destinations, "Resorts" : Resorts} )

def contactus(request,template="contactus.html"):
    return render(request,template)
    
def Rajasthan(request, template="Rajasthan.html"):
    return render(request, template)

def Invoice(request, template="Invoice.html"):
    package ={
    "Date" : "01/01/2022",
    "DestinationId" : 0,
    "NoOfDay" : 7,
    "NoOfMember" : 5,
    "PackageId" : 0,
    "Price" : 45000,
    "ResortId" : 0,
    "RoomIds" : [ 0, 1, 3 ],
    "UserId" : 0
    }
    return render(request,template,{"Package":package})

def openResorts(request,id,template="Resorts.html"):
    Filtered_Resorts = [r for r in Resorts if r['DestinationId'] == id]

    for d in Destinations:
        if (d["DestinationId"] == id):
            tempDName = d["Name"]
    
    return render(request,template,{"DId":id,"DName":tempDName,"Resorts":Filtered_Resorts})
    
def openRooms(request,id,rid,template="Rooms.html"):
    if CurrentUser.Role != None:
        Filtered_Rooms = [r for r in Rooms if r['ResortId'] == rid]

        return render(request,template,{"DName":tempDName,"Rooms":Filtered_Rooms,"CurrentUser":CurrentUser})
    else:
        return render(request,"login.html")

login/views.py
from django.shortcuts import render, redirect
from firebaseConfig import database,CurrentUser,User

# Create your views here.

def getUsers():
  return database.child("Users").get().val()

def index(request, template="login.html"):
    return render(request, template)

def loginUser(request):
  print("test")
  email = request.POST["loginEmail"]
  password = request.POST["loginPassword"]

  for i in getUsers():
    if(i["Email"] == email and i["Password"] == password):
        CurrentUser.Email = i["Email"]
        CurrentUser.FirstName = i["FirstName"]
        CurrentUser.LastName = i["LastName"]
        CurrentUser.Mobile = i["Mobile"]
        CurrentUser.Password = i["Password"]
        CurrentUser.Role = i["Role"]
        CurrentUser.UserId = i["UserId"]

        Destinations  = database.child("Destinations").get().val()
        Resorts = database.child("Resorts").get().val()

        print(CurrentUser.Role)
        
        return render(request, "homepage.html", {"Destinations": Destinations, "Resorts" : Resorts} )
        
    else:
        print("Invalid Login")

def signupUser(request):
  fname = request.POST["signupFName"]
  lname = request.POST["signupLName"]
  uid = len(getUsers)
  email = request.POST["signupEmail"]
  mobileno = request.POST["signupMobileNo"]
  role = "User"
  password = request.POST["signupPassword"]

  for i in getUsers():
    if(i["Email"] != email):
      tempUsers = database.child("Users").get().val()
      database.child("Users").child(len(tempUsers)).set({
        "Email" :  email,
        "FirstName" : fname,
        "LastName" : lname,
        "Mobile" : int(mobileno),
        "Password" : password,
        "Role" : role,
        "UserId" : uid
      })
    else:
      print("Already Registered")
  return redirect(request, "login", {"Users": getUsers} )

manageDestinations/views.py
from django.shortcuts import render
from firebaseConfig import database

# Create your views here.
def getDestinations():
  return database.child("Destinations").get().val()

def index(request, template="manageDestinations.html"):
  return render(request, template, {"Destinations": getDestinations})

def addNewDestinations(request):
  tempDest = database.child("Destinations").get().val()

  dname = request.POST["destName"]
  daddress = request.POST["destCity"]
  dcity = request.POST["destCity"]
  ddescription = request.POST["destDescription"]
  did = len(tempDest)
  Image = "https://previews.123rf.com/images/dragomirescu/dragomirescu1808/dragomirescu180800451/105737910-destination-word-hand-writing-text-typography-design-with-black-and-orange-color-suitable-for-logo-b.jpg"

  database.child("Destinations").child(len(tempDest)).set({
    "Address" : daddress,
    "City" : dcity,
    "Description" : ddescription,
    "DestinationId" : did,
    "Image" : Image,
    "Name" : dname
  })
  return render(request, "manageDestinations.html", {"Destinations": getDestinations} )

manageResorts/views.py
from django.shortcuts import render
from firebaseConfig import database

# Create your views here.
def getDestinations():
    return database.child("Destinations").get().val()

def getResorts():
  return database.child("Resorts").get().val()


def index(request, template="manageResorts.html"):
  return render(request, template, {"Resorts": getResorts,"Destinations" : getDestinations})

def addNewResort(request):
  tempRest = database.child("Resorts").get().val()
  tempDID = request.POST["restDestId"]

  database.child("Resorts").child(len(tempRest)).set({
    "City":request.POST["restCity"],
    "BasePrice":int(request.POST["restBasePrice"]),
    "Address" : request.POST["restAddress"],
    "Description" : request.POST["restDescription"],
    "DestinationId" : int(tempDID),
    "Image" : "https://thumbs.dreamstime.com/z/resorts-orange-color-word-text-logo-icon-suitable-card-typography-design-127994353.jpg",
    "IsAvailable" : request.POST["restIsAvail"],
    "IsMeal" : request.POST["restIsMeal"],
    "Name" : request.POST["restName"],
    "ResortId" : len(tempRest)
  })
  return render(request, "manageResorts.html", {"Resorts": getResorts,"Destinations" : getDestinations} )

manageUsers/views.py
from django.shortcuts import render
from firebaseConfig import database

def getUsers():
  return database.child("Users").get().val()

def index(request, template="manageUsers.html"):
  return render(request, template, {"Users": getUsers} )

def addNewUser(request):
  fname = request.POST["fname"]
  lname = request.POST["lname"]
  uid = request.POST["uid"]
  email = request.POST["email"]
  mobileno = request.POST["mobileno"]
  role = request.POST["role"]
  password = "User@123"

  tempUsers = database.child("Users").get().val()
  database.child("Users").child(len(tempUsers)).set({
    "Email" :  email,
    "FirstName" : fname,
    "LastName" : lname,
    "Mobile" : int(mobileno),
    "Password" : password,
    "Role" : role,
    "UserId" : uid
  })
  return render(request, "manageUsers.html", {"Users": getUsers} )

templates/Invoice.html
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
        <title>Divine</title>

		<link rel="shortcut icon" type="image/icon" href="{% static 'logo/favicon.png' %}"/>
        <link rel="stylesheet" href="{% static 'css/invoice_css.css' %}">
	</head>
	<body>
		<header>
			<h1>Invoice</h1>
			<address contenteditable>
				<p>The Divine Holiday</p>
				<p>Main Branch<br>Ahmedabad</p>
				<p>(+91) 9876543210</p>
			</address>
		</header>
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<div class="text-gray-light">INVOICE TO:</div>
				<p>The Divine Holiday</p>
			</address>
			<table class="meta">
				<tr>
					<th><span contenteditable>Invoice #</span></th>
					<td><span contenteditable>0002</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Date</span></th>
					<td><span contenteditable>January 1, 2022</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Due</span></th>
					<td><span id="prefix" contenteditable>₹</span><span>1.00</span></td>
				</tr>
			</table>
			<table class="inventory">
				<thead>
					<tr>
						<th><span contenteditable>Resort</span></th>
						<th><span contenteditable>Room</span></th>
						<th><span contenteditable>Rate Per Day</span></th>
						<th><span contenteditable>No Of Day</span></th>
						<th><span contenteditable>Total Price</span></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><a class="cut">-</a><span contenteditable></span></td>
						<td><span contenteditable></span></td>
						<td><span data-prefix>₹</span><span contenteditable>1.00</span></td>
						<td><span contenteditable>1</span></td>
						<td><span data-prefix>₹</span><span>1.00</span></td>
					</tr>
				</tbody>
			</table>
			<a class="add">+</a>
			<table class="balance">
				<tr>
					<th><span contenteditable>Total</span></th>
					<td><span data-prefix>₹</span><span>1.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Paid</span></th>
					<td><span data-prefix>₹</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Balance Due</span></th>
					<td><span data-prefix>₹</span><span>1.00</span></td>
				</tr>
			</table>
		</article>
		<aside>
			<h1><span contenteditable>Additional Notes</span></h1>
			<div contenteditable>
				<p>A finance charge of 1.5% will be made on unpaid balances after 30 days.</p>
			</div>
		</aside>
        <script src="{% static 'js/invoice_js.js' %}"></script>

	</body>
</html>

templates/Resorts.html
{% load static %}
<!doctype html>
<html class="no-js"  lang="en">

	<head>
        <title>Divine Holidays</title>
		<!-- META DATA -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        
        
		<!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet" />

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet" />

		<!-- TITLE OF SITE -->
		<title>Divine Holidays</title>

		<!-- favicon img -->
		<link rel="shortcut icon" type="image/icon" href="{% static 'logo/favicon.png' %}"/>

		<!--font-awesome.min.css-->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />

		<!--animate.css-->
		<link rel="stylesheet" href="{% static 'css/animate.css' %}" />

		<!--hover.css-->
		<link rel="stylesheet" href="{% static 'css/hover-min.css' %}">

		<!--datepicker.css-->
		<link rel="stylesheet"  href="{% static 'css/datepicker.css' %}" >

		<!--owl.carousel.css-->
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}"/>

		<!-- range css-->
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />

		<!--bootstrap.min.css-->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

		<!-- bootsnav -->
		<link rel="stylesheet" href="{% static 'css/bootsnav.css' %}"/>

		<!--style.css-->
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />

		<!--responsive.css-->
		<link rel="stylesheet" href="{% static 'css/responsive.css' %}" />

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	<style>
			* {box-sizing: border-box;}
			body {font-family: Verdana, sans-serif;}
			.mySlides {display: none;}
			img {vertical-align: middle;}
			
			/* Slideshow container */
			.slideshow-container {
			  max-width: 1000px;
			  position: relative;
			  margin: auto;
			}
			
			/* Caption text */
			.text {
			  color: #f2f2f2;
			  font-size: 15px;
			  padding: 8px 12px;
			  position: absolute;
			  bottom: 8px;
			  width: 100%;
			  text-align: center;
			}
			
			/* Number text (1/3 etc) */
			.numbertext {
			  color: #f2f2f2;
			  font-size: 12px;
			  padding: 8px 12px;
			  position: absolute;
			  top: 0;
			}
			
			/* The dots/bullets/indicators */
			.dot {
			  height: 15px;
			  width: 15px;
			  margin: 0 2px;
			  background-color: #bbb;
			  border-radius: 50%;
			  display: inline-block;
			  transition: background-color 0.6s ease;
			}
			
			.active {
			  background-color: #717171;
			}
			
			/* Fading animation */
			.fade {
			  -webkit-animation-name: fade;
			  -webkit-animation-duration: 1.5s;
			  animation-name: fade;
			  animation-duration: 1.5s;
			}
			
			@-webkit-keyframes fade {
			  from {opacity: .4} 
			  to {opacity: 1}
			}
			
			@keyframes fade {
			  from {opacity: .4} 
			  to {opacity: 1}
			}
			
			/* On smaller screens, decrease text size */
			@media only screen and (max-width: 300px) {
			  .text {font-size: 11px}
			}
			</style>
			<style>
				.button {
				  background-color: #0099ff;
				  border: none;
				  color: white;
				/*  padding: 15px 32px;*/
				  text-align: center;
				  text-decoration: none;
				  display: inline-block;
				 /* font-size: 10px;
				  margin: 4px 2px;*/
				  cursor: pointer;
				  width:110px;
                  height:50px;
				}
				.button:hover {
  					background-color: red;
  					color: white;
                }
	</style>
	</head>
    <body>
            
		<!--header start -->
		{% comment %} <section id="home" class="about-us">
			<div class="container">
				<div class="about-us-content">
					<div class="row">
						<div class="col-sm-12">
							<div class="single-about-us">
								<div class="about-us-txt">
									<h2>
										Explore the Beauty of the Beautiful World 

									</h2>
									<div class="about-btn">
										<button  class="about-view">
											explore now
										</button>
									</div><!--/.about-btn-->
								</div><!--/.about-us-txt-->
							</div><!--/.single-about-us-->
						</div><!--/.col-->
						<div class="col-sm-0">
							<div class="single-about-us">
								
							</div><!--/.single-about-us-->
						</div><!--/.col-->
					</div><!--/.row-->
				</div><!--/.about-us-content-->
			</div><!--/.container-->

		</section> {% endcomment %}
		<!--/.about-us-->
		<!--about-us end -->
		<section style="height: max-content;">
			<div class="container">
			<div class="slideshow-container">
	
				<div class="mySlides fade">
				 <a href="package"><img src="{% static 'images/goapackage/goa1.jpg' %}" alt="portfolio image"/>
					
				</a>
				 
				</div>
				
				<div class="mySlides fade">
				 <a href="package"><img src="{% static 'images/goapackage/goa21.jpg' %}" alt="portfolio image"/> 
					
				</a>
				 
				</div>
				
				<div class="mySlides fade">
				  <img src="{% static 'images/goapackage/goa31.jpg' %}" alt="portfolio image"/> 
				</div>
				
				</div>
				<br>
				
				<div style="text-align:center">
				  <span class="dot"></span> 
				  <span class="dot"></span> 
				  <span class="dot"></span> 
				</div>
				
				<script>
				var slideIndex = 0;
				showSlides();
				
				function showSlides() {
				  var i;
				  var slides = document.getElementsByClassName("mySlides");
				  var dots = document.getElementsByClassName("dot");
				  for (i = 0; i < slides.length; i++) {
					slides[i].style.display = "none";  
				  }
				  slideIndex++;
				  if (slideIndex > slides.length) {slideIndex = 1}    
				  for (i = 0; i < dots.length; i++) {
					dots[i].className = dots[i].className.replace(" active", "");
				  }
				  slides[slideIndex-1].style.display = "block";  
				  dots[slideIndex-1].className += " active";
				  setTimeout(showSlides, 4000); // Change image every 2 seconds
				}
				</script>
			</div>
			</section>


        <section style="height: max-content;">

            <div class="gallary-header text-center">
			   <h2 align="center" >
				   <br>Best {{DName}} Packages
			   </h2><br>
            </div>
			{% if Resorts%}
               {% for r in Resorts%}
               <br>
                <div style="width: 25%; float:left; background-color: #F0FFFF; height: 190px; width:1450px;">
                    <div class="row" style="margin:15px;border:1px solid black;">
                        <div class="col-sm-3">
                            <img src="{{r.Image}}" alt="portfolio image"/> 
                        </div>
                        <div class="col-sm-6">
                            <div class="row">
                                <div class="col-sm-8">
                                    <p><b>{{r.Name}}</b></p>
                                </div>
                                <div class="col-sm-4">
                                    <p><b> 2 Nights 3 days</b></p>
                                </div>
                            </div>
                            <div>
                                <p>{{r.City}}</p>
                                <p>{{r.Description}}</p>
                                <p>
                                {% if r.IsMeal%}
                                    <span>Rooms Available</span>
                                {% endif %}
                                </p>
                                <p>
                                {% if r.IsMeal%}
                                    <span>Meal Included</span>
                                {% endif %}
                                </p>
                            </div>

                            
                        </div>
                        <div class="col-sm-3">
                            <br>
                            <b><center>Base Price<br>₹{{r.BasePrice}}</center></b><br>
                            <!--<button type="button" class="button">Book Now</button>-->
                            <center>
                                <a href="{% url 'home:package' id=DId rid=r.ResortId%}">	
                                <button type="button" style="background-color: #00BFFF; height: 50px; width: 180px; font-size: 20px;">Book now</button>
                                </a>
                            </center><br>
                        </div>
                    </div>
                </div>
               {%endfor%}
            {% endif %}
			</section>
            
            <!-- footer-copyright start -->
            <div class="row">
            </div>
		<footer  class="footer-copyright">
			<div class="container">
				<div class="footer-content">
					<div class="row">
						<div class="col-sm-3">
							<div class="single-footer-item">
								<div class="footer-logo">
									<a href="index.html">
										Divine<span>Holidays</span>
									</a>
									<p>
										best travel agency
									</p>
								</div>
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item">
								<h2>link</h2>
								<div class="single-footer-txt">
									<p><a href="#">home</a></p>
									<p><a href="#">destination</a></p>
									<p><a href="#">spacial packages</a></p>
									<p><a href="#">special offers</a></p>
									<p><a href="#">blog</a></p>
									<p><a href="#">contacts</a></p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->

						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item">
								<h2>popular destination</h2>
								<div class="single-footer-txt">
									<p><a href="#">Goa</a></p>
									<p><a href="#">Kerala</a></p>
									<p><a href="#">Himachal </a></p>
									<p><a href="#">Uttarakhand</a></p>
									<p><a href="#">Manali</a></p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

						<div class="col-sm-3">
							<div class="single-footer-item text-center">
								<h2 class="text-left">contacts</h2>
								<div class="single-footer-txt text-left">
									<p>+91 9428740696</p>
									<p class="foot-email"><a href="#">info@divineholidays.com</a></p>
									<p>Iskcon Cross Road, Ahmedabad </p>
									<p>Gujarat, India</p>
								</div><!--/.single-footer-txt-->
							</div><!--/.single-footer-item-->
						</div><!--/.col-->

					</div><!--/.row-->

				</div><!--/.footer-content-->
				<hr>
				<div class="foot-icons ">
					<ul class="footer-social-links list-inline list-unstyled">
		                <li><a href="#" target="_blank" class="foot-icon-bg-1"><i class="fa fa-facebook"></i></a></li>
		                <li><a href="#" target="_blank" class="foot-icon-bg-2"><i class="fa fa-twitter"></i></a></li>
		                <li><a href="#" target="_blank" class="foot-icon-bg-3"><i class="fa fa-instagram"></i></a></li>
		        	</ul>
		        	<p>&copy; 2017 <a href="https://www.themesine.com">ThemeSINE</a>. All Right Reserved</p>

		        </div><!--/.foot-icons-->
				<div id="scroll-Top">
					<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
				</div><!--/.scroll-Top-->
			</div><!-- /.container-->

		</footer><!-- /.footer-copyright-->
		<!-- footer-copyright end -->




		<script src="{% static 'js/jquery.js' %}"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->

		<!--modernizr.min.js-->
		<script  src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>


		<!--bootstrap.min.js-->
		<script  src="{% static 'js/bootstrap.min.js' %}"></script>

		<!-- bootsnav js -->
		<script src="{% static 'js/bootsnav.js' %}"></script>

		<!-- jquery.filterizr.min.js -->
		<script src="{% static 'js/jquery.filterizr.min.js' %}"></script>

		<script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

		<!--jquery-ui.min.js-->
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>

        <!-- counter js -->
		<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
		<script src="{% static 'js/waypoints.min.js' %}"></script>

		<!--owl.carousel.js-->
        <script  src="{% static 'js/owl.carousel.min.js' %}"></script>

        <!-- jquery.sticky.js -->
		<script src="{% static 'js/jquery.sticky.js' %}"></script>

        <!--datepicker.js-->
        <script  src="{% static 'js/datepicker.js' %}"></script>

		<!--Custom JS-->
		<script src="{% static 'js/custom.js' %}"></script>

    </body>
</html>

templates/index.html
<p> Hello World </p>